markdownExploder: true
projectBrief:
  projectBriefFile: docs/project-brief.md
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
  featureFilePattern: feature-{n}.{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
uiDevLoadAlwaysFiles:
  - docs/architecture/ui-coding-standards.md
  - docs/architecture/ui-tech-stack.md
  - docs/architecture/ui-source-tree.md
  - docs/architecture/component-patterns.md
  - docs/architecture/theme-tokens.md
uiDevFolder: null
devStoryLocation: docs/stories
devStoryPattern: story-{n}.{n}.{n}*.md
agentCoreDump: .ai/core-dump{n}.md
